export const expenseListStyles = {
  list: 'flex flex-col',
} as const;

export const receiptUploaderStyles = {
  root: 'space-y-3',
  header: 'flex items-center justify-between',
  label: 'text-xs font-semibold tracking-wider uppercase text-slate-400',
  hint: 'text-xs text-slate-500',
  attachmentList: 'space-y-2',
  attachment: 'flex items-center justify-between p-3 rounded-xl border border-slate-700/60 bg-slate-900/40',
  fileMeta: 'flex items-center space-x-3 overflow-hidden',
  fileIcon: 'p-2 rounded-lg bg-indigo-500/10 text-indigo-400',
  truncate: 'truncate',
  fileName: 'text-sm font-medium text-slate-200 truncate',
  fileSize: 'text-xs text-slate-400',
  actions: 'flex items-center space-x-2',
  viewLink: 'p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition',
  deleteButton: 'p-1.5 rounded-lg text-rose-400 hover:text-rose-300 hover:bg-rose-500/10 transition',
  pending: 'flex items-center justify-between p-3 rounded-xl border border-indigo-500/40 bg-indigo-500/5',
  thumbnail: 'w-10 h-10 rounded-lg object-cover border border-indigo-500/30 cursor-pointer',
  clearButton: 'p-1.5 rounded-lg text-slate-400 hover:text-rose-400 hover:bg-slate-800 transition',
  dropzone: 'cursor-pointer flex flex-col items-center justify-center p-5 rounded-xl border-2 border-dashed transition text-center',
  dropzoneActive: 'border-indigo-500 bg-indigo-500/10',
  dropzoneIdle: 'border-slate-700/80 hover:border-slate-600 bg-slate-900/20 hover:bg-slate-900/40',
  dropzoneDisabled: 'opacity-50 cursor-not-allowed',
  fileInput: 'hidden',
  uploadIcon: 'p-2.5 mb-2 rounded-full bg-slate-800 text-slate-400',
  uploadTitle: 'text-xs font-medium text-slate-300',
  uploadHint: 'text-[11px] text-slate-500 mt-0.5',
  modal: 'fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4',
  modalFrame: 'relative max-w-3xl max-h-[90vh]',
  modalImage: 'max-h-[85vh] max-w-full rounded-xl object-contain',
  modalClose: 'absolute top-2 right-2 p-2 rounded-full bg-slate-900/80 text-white hover:bg-slate-800',
} as const;
