import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        background: 'var(--bb-bg)',
        'background-elevated': 'var(--bb-bg-elevated)',
        surface: 'var(--bb-surface)',
        'surface-container': 'var(--bb-surface-container)',
        'surface-container-low': 'var(--bb-surface-container-low)',
        'surface-container-high': 'var(--bb-surface-container-high)',
        'surface-container-highest': 'var(--bb-surface-container-highest)',
        'surface-elevated': 'var(--bb-surface-elevated)',
        'surface-bright': 'var(--bb-surface-bright)',
        'surface-hover': 'var(--bb-surface-hover)',
        text: 'var(--bb-text)',
        'text-secondary': 'var(--bb-text-secondary)',
        'text-tertiary': 'var(--bb-text-tertiary)',
        primary: 'var(--bb-primary)',
        'primary-muted': 'var(--bb-primary-muted)',
        'primary-soft': 'var(--bb-primary-soft)',
        'on-primary': 'var(--bb-on-primary)',
        'primary-container': 'var(--bb-primary-container)',
        secondary: 'var(--bb-secondary)',
        'secondary-fixed': 'var(--bb-secondary-fixed)',
        'secondary-container': 'var(--bb-secondary-container)',
        border: 'var(--bb-border)',
        'border-subtle': 'var(--bb-border-subtle)',
        'input-bg': 'var(--bb-input-bg)',
        success: 'var(--bb-success)',
        'success-soft': 'var(--bb-success-soft)',
        danger: 'var(--bb-danger)',
        'danger-soft': 'var(--bb-danger-soft)',
        warning: 'var(--bb-warning)',
        'warning-soft': 'var(--bb-warning-soft)',
        violet: 'var(--bb-violet)',
        rose: 'var(--bb-rose)',
        emerald: 'var(--bb-emerald)',
        ocean: 'var(--bb-ocean)',
        'gradient-start': 'var(--bb-gradient-start)',
        'gradient-end': 'var(--bb-gradient-end)',
        'tab-bar': 'var(--bb-tab-bar)',
        'tab-bar-border': 'var(--bb-tab-bar-border)',
        overlay: 'var(--bb-overlay)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        section: '24px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        card: '20px',
        xl: '24px',
        nav: '28px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Fraunces', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
};

export default config;
