export const aiCoachStyles = {
  screen: 'h-full flex flex-col bg-background',
  transcript: 'flex-1 overflow-y-auto flex flex-col gap-3',
  emptyHero: 'relative rounded-2xl p-6 sm:p-9 text-center overflow-hidden my-auto border border-borderSubtle dark:border-white/10',
  heroMark: 'flex justify-center mb-4',
  heroTitle: 'm-0 font-sans text-lg font-extrabold text-text tracking-tight',
  heroCopy: 'my-2 mx-auto mb-5 text-[13px] text-textSecondary font-sans leading-5 max-w-[360px]',
  chipRow: 'flex flex-wrap justify-center gap-2',
  chip: 'inline-flex items-center gap-1.5 bg-black/5 dark:bg-white/5 py-1 px-3 rounded-full text-[11px] font-semibold text-textSecondary',
  stack: 'flex flex-col gap-4',
  stackTight: 'flex flex-col gap-2',
  userRow: 'flex justify-end',
  assistantRow: 'flex justify-start',
  userBubble: 'max-w-[80%] px-4 py-3 rounded-2xl rounded-br-[4px] bg-primary text-white text-sm leading-5',
  assistantBubble: 'max-w-[88%] px-4 py-3.5 rounded-2xl rounded-bl-[4px] bg-surfaceHover text-text border border-borderSubtle dark:border-white/10 text-sm leading-5',
  pendingRow: 'flex justify-start',
  pendingBubble: 'p-3 px-4 rounded-2xl rounded-bl-[4px] bg-surfaceHover',
  pendingDots: 'flex gap-1',
  pendingDot: 'w-1.5 h-1.5 rounded-full bg-textTertiary',
  composer: 'border-t border-borderSubtle bg-background',
  errorRow: 'mb-2 cursor-pointer',
} as const;
